"""Public semantic error taxonomy."""

from datamonger._errors import (
    ArtifactIntegrityError,
    ArtifactSelectionError,
    ArtifactUnavailableError,
    CacheError,
    DatamongerError,
    DecodedIntegrityError,
    DecodeError,
    OfflineError,
    RegistryError,
    RegistryIntegrityError,
    RegistryOfflineError,
    RegistryReleaseError,
    RegistryRetrievalError,
    RetrievalError,
    RetrievalLocationsError,
    UnknownDatasetError,
    UnsupportedDecoderError,
    UnsupportedRegistryError,
)

__all__ = [
    "ArtifactIntegrityError",
    "ArtifactSelectionError",
    "ArtifactUnavailableError",
    "CacheError",
    "DatamongerError",
    "DecodeError",
    "DecodedIntegrityError",
    "OfflineError",
    "RegistryError",
    "RegistryIntegrityError",
    "RegistryOfflineError",
    "RegistryReleaseError",
    "RegistryRetrievalError",
    "RetrievalError",
    "RetrievalLocationsError",
    "UnknownDatasetError",
    "UnsupportedDecoderError",
    "UnsupportedRegistryError",
]
