name: Versionary

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

concurrency:
  group: versionary-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.RELEASE_TOKEN }}

      - id: versionary
        uses: jolars/versionary@5009f8dee643598ffc3744c0fb67d57b42f9a81d # v1.4.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          versionary-version: 1.4.0
